//! Integration tests for the `polyforge-cli ledger export --otel` command.
//!
//! Golden fixtures live in `tests/fixtures/*.jsonl` as chain-consistent
//! Merkle ledgers generated by the real CLI (`append model_claim` - the
//! claim payload doubles as the opaque `ts` slot). Each test copies one
//! fixture into a unique temp dir, synthesizes the `.anchor` sidecar the
//! fail-closed chain verifier requires, then spawns the REAL binary
//! (`env!("CARGO_BIN_EXE_polyforge-cli")`) and asserts on the OTLP/JSON
//! output.
//!
//! Timestamp policy under test (see `ts_to_nanos` in main.rs):
//! - all-digits `ts` is epoch milliseconds -> nanos via *1_000_000;
//! - strict RFC3339 subset strings are parsed by hand;
//! - anything else (prose, overflow) omits BOTH OTLP time fields while the
//!   raw `ts` always travels verbatim in attributes.

use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicU64, Ordering};

static COUNTER: AtomicU64 = AtomicU64::new(0);

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

struct Env {
    ledger: PathBuf,
}

impl Env {
    /// Materialize a golden fixture as a runnable ledger: copy the JSONL and
    /// rebuild the anchor sidecar (`<ledger>.anchor`) from the chain head so
    /// the fail-closed verifier accepts it.
    fn from_fixture(name: &str) -> Self {
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let dir = std::env::temp_dir().join(format!(
            "polyforge-export-otel-{name}-{}-{n}",
            std::process::id()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let src = fixture_dir().join(format!("{name}.jsonl"));
        let ledger = dir.join("ledger.jsonl");
        std::fs::copy(&src, &ledger).unwrap_or_else(|e| panic!("copy fixture {src:?}: {e}"));
        write_anchor(&ledger);
        Self { ledger }
    }
}

/// Rebuild the anchor sidecar (entry count + head hash) from the ledger
/// contents. Mirrors the private `Anchor` shape in polyforge-core's ledger:
/// `{"entry_count": <lines>, "head_hash": <last entry hash>}`.
fn write_anchor(ledger: &Path) {
    let text = std::fs::read_to_string(ledger).expect("read copied fixture");
    let lines: Vec<&str> = text.lines().filter(|l| !l.trim().is_empty()).collect();
    let last: serde_json::Value = serde_json::from_str(lines.last().expect("non-empty fixture"))
        .expect("fixture last line is valid JSON");
    let anchor = serde_json::json!({
        "entry_count": lines.len(),
        "head_hash": last["hash"],
    });
    let mut anchor_path = ledger.as_os_str().to_owned();
    anchor_path.push(".anchor");
    std::fs::write(anchor_path, anchor.to_string()).expect("write anchor sidecar");
}

fn pf(env: &Env, args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_polyforge-cli"))
        .args(args)
        .env("PF_LEDGER", &env.ledger)
        .output()
        .expect("failed to spawn polyforge-cli binary")
}

fn assert_ok(out: &Output, what: &str) {
    assert_eq!(
        out.status.code().expect("no exit code"),
        0,
        "{what} should exit 0\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
}

/// Run a fail-closed export against the env's ledger and return the parsed
/// logRecords array of the single resourceLogs/scopeLogs pair.
fn export_records(env: &Env) -> Vec<serde_json::Value> {
    let out = pf(env, &["ledger", "export", "--otel"]);
    assert_ok(&out, "pf ledger export --otel");
    let doc: serde_json::Value =
        serde_json::from_slice(&out.stdout).expect("export stdout parses as JSON");
    doc["resourceLogs"][0]["scopeLogs"][0]["logRecords"]
        .as_array()
        .expect("logRecords array")
        .clone()
}

/// Look up one attribute's stringValue in an OTLP log record.
fn attr_value<'a>(rec: &'a serde_json::Value, key: &str) -> Option<&'a str> {
    rec["attributes"]
        .as_array()?
        .iter()
        .find(|a| a["key"] == key)
        .and_then(|a| a["value"]["stringValue"].as_str())
}

/// (a) A prose `ts` ("implemented auth module") is unparseable: both OTLP
/// time fields must be OMITTED while the raw prose still rides in attrs.
#[test]
fn prose_ts_record_has_no_time_fields() {
    let env = Env::from_fixture("fixture-prose-ts");
    let records = export_records(&env);
    assert_eq!(records.len(), 1, "prose fixture holds exactly one entry");
    let rec = &records[0];
    assert!(
        rec.get("timeUnixNano").is_none(),
        "prose ts must omit timeUnixNano, got {:?}",
        rec.get("timeUnixNano")
    );
    assert!(
        rec.get("observedTimeUnixNano").is_none(),
        "prose ts must omit observedTimeUnixNano, got {:?}",
        rec.get("observedTimeUnixNano")
    );
    assert_eq!(
        attr_value(rec, "ts"),
        Some("implemented auth module"),
        "raw prose ts must survive verbatim in attributes"
    );
}

/// (b) An all-digits `ts` is epoch milliseconds: "1700000000000" maps to
/// exactly "1700000000000000000" nanos in BOTH time fields.
#[test]
fn epoch_ts_converts_exactly() {
    let env = Env::from_fixture("fixture-epoch-ts");
    let records = export_records(&env);
    assert_eq!(records.len(), 1, "epoch fixture holds exactly one entry");
    let rec = &records[0];
    assert_eq!(
        rec["timeUnixNano"].as_str(),
        Some("1700000000000000000"),
        "millis*1e6 conversion must be exact"
    );
    assert_eq!(
        rec["observedTimeUnixNano"].as_str(),
        Some("1700000000000000000"),
        "observedTimeUnixNano mirrors timeUnixNano"
    );
}

/// (c) The RFC3339 subset parser converts "2026-08-21T12:00:00Z" to epoch
/// nanos. Expected value computed independently here: 2026-08-21T12:00:00Z
/// is 1787313600 seconds after the Unix epoch.
#[test]
fn rfc3339_converts_exactly() {
    let env = Env::from_fixture("fixture-mixed");
    let records = export_records(&env);
    assert_eq!(records.len(), 3, "mixed fixture holds three entries");
    let rec = &records[0];
    assert_eq!(
        attr_value(rec, "ts"),
        Some("2026-08-21T12:00:00Z"),
        "first mixed entry must be the RFC3339 one"
    );
    let expected_nanos = (1_787_313_600_i64 * 1_000_000_000).to_string();
    assert_eq!(
        rec["timeUnixNano"].as_str(),
        Some(expected_nanos.as_str()),
        "RFC3339 Z timestamp must convert exactly"
    );
    assert_eq!(
        rec["observedTimeUnixNano"].as_str(),
        Some(expected_nanos.as_str()),
        "observedTimeUnixNano mirrors timeUnixNano"
    );
}

/// (d) An all-digits `ts` that overflows u64 millis ("99999999999999999999",
/// 20 digits) yields None: both time fields omitted, raw digits preserved.
#[test]
fn overflow_ts_omits_time_fields() {
    let env = Env::from_fixture("fixture-mixed");
    let records = export_records(&env);
    let rec = &records[1];
    assert_eq!(
        attr_value(rec, "ts"),
        Some("99999999999999999999"),
        "second mixed entry must be the overflow one"
    );
    assert!(
        rec.get("timeUnixNano").is_none(),
        "overflowing ts must omit timeUnixNano"
    );
    assert!(
        rec.get("observedTimeUnixNano").is_none(),
        "overflowing ts must omit observedTimeUnixNano"
    );
}

/// (e) Round trip: the whole export parses as OTLP/JSON and EVERY log record
/// carries a non-empty task_id attribute (identity never lost in transit).
#[test]
fn round_trip_and_task_id() {
    let env = Env::from_fixture("fixture-mixed");
    let records = export_records(&env);
    assert_eq!(records.len(), 3);
    for (i, rec) in records.iter().enumerate() {
        let task_id = attr_value(rec, "task_id")
            .unwrap_or_else(|| panic!("record {i} missing task_id attribute"));
        assert!(!task_id.is_empty(), "record {i} task_id must be non-empty");
    }
    // Spot-check identity survives verbatim for two known fixtures entries.
    assert_eq!(attr_value(&records[0], "task_id"), Some("mixed-rfc3339"));
    assert_eq!(attr_value(&records[2], "task_id"), Some("mixed-epoch"));
}

/// (f) `--out <path>` writes byte-identical output to a stdout run of the
/// same ledger: the flag changes the sink, never the bytes.
#[test]
fn out_flag_writes_identical_bytes() {
    let env = Env::from_fixture("fixture-mixed");
    let out_path = env.ledger.parent().unwrap().join("export-out.json");

    let via_file = pf(
        &env,
        &[
            "ledger",
            "export",
            "--otel",
            "--out",
            out_path.to_str().unwrap(),
        ],
    );
    assert_ok(&via_file, "pf ledger export --otel --out");
    let file_bytes = std::fs::read(&out_path).expect("--out file exists");

    let via_stdout = pf(&env, &["ledger", "export", "--otel"]);
    assert_ok(&via_stdout, "pf ledger export --otel (second run)");

    assert_eq!(
        file_bytes, via_stdout.stdout,
        "--out bytes must equal stdout bytes"
    );
}
